!classDefinition: #Pepe category: #'EJ1-p1'!
DenotativeObject subclass: #Pepe
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'EJ1-p1'!

"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'Pepe class' category: #'EJ1-p1'!
Pepe class
	instanceVariableNames: ''!

!Pepe class methodsFor: 'saludos' stamp: 'VS 8/26/2025 16:24:26'!
hola

^'chau' ! !
